project_id = "uxreusxycozxpifaeeyq"

[functions.send-nurture-emails]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.analyze-meal]
verify_jwt = false
