// This file is automatically generated. Do not edit it directly.
import { Capacitor } from "@capacitor/core";
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const onNativeBridge =
  typeof window !== "undefined" &&
  window.location.pathname.includes("/app/auth/native-bridge");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Native bridge must not consume the PKCE code (verifier lives in the iOS app).
    // Native app exchanges the code explicitly from the deep-link handler.
    detectSessionInUrl: !Capacitor.isNativePlatform() && !onNativeBridge,
    flowType: "pkce",
  }
});